language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t artir3/docker-multiconteiner -f ./client/Dockerfile.dev ./client/

script:
  - docker run -e CI=true artir3/docker-multiconteiner npm run test

after_success:
  - docker build -t artir3/docker-course-client ./client
  - docker build -t artir3/docker-course-nginx ./nginx
  - docker build -t artir3/docker-course-server ./server
  - docker build -t artir3/docker-course-worker ./worker
  # Log in to the docker CLI
  - echo "$docHash" | docker login -u "$docId" --password-stdin
  # Take those images and push them to docker hub
  - docker push artir3/docker-course-client
  - docker push artir3/docker-course-nginx
  - docker push artir3/docker-course-server
  - docker push artir3/docker-course-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "docker-multiconteiner"
  env: "DockerMulticonteiner-env"
  bucket_name: "elasticbeanstalk-eu-central-1-701321592228"
  bucket_path: "docker-multiconteiner"
  on:
    branch: master
  access_key_id: 
    secure: "$ACCESS_KEY_ID"
  secret_access_key:
    secure: "$SECRET_KEY"